#!/usr/bin/env python3
"""Writes vectors/v1.json from the Python reference. Once v1 is released, never run this again:
a change in the output means a change in the format, which needs a new tag (v2) and a new file.
Every input here is fake and public: the seeds are hashes of words, the addresses are patterns."""
import json, os, sys
from hashlib import sha256

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "python"))
import sign_and_burn as sb

HERE = os.path.dirname(os.path.abspath(__file__))
x = lambda b: "0x" + b.hex()     # 0x-prefixed, so Foundry and viem read it as is
fake = lambda word: sha256(word.encode()).digest()          # a 32-byte stand-in for any hash or seed
addr = lambda byte: bytes([byte]) * 20                       # 0x1111…, 0x2222…

# (name, chain id, curve signer, seat number, n, message m) -- m is None to derive it from c
CASES = [
    ("base-sepolia-first", 84532, addr(0x11), 0, 0, None),
    ("second-key", 84532, addr(0x11), 0, 1, None),
    ("other-seat-number", 84532, addr(0x11), 7, 2, None),
    ("other-signer-and-chain", 1, addr(0xAB), 0, 0, None),
    ("big-numbers", 2**64 + 8453, addr(0x22), 2**32 - 1, 2**64 - 2, None),   # the last n that has a next key
    ("message-all-zero", 84532, addr(0x11), 0, 3, bytes(32)),       # checksum 960 = 0x3c0, the most
    ("message-all-ones", 84532, addr(0x11), 0, 4, b"\xff" * 32),    # checksum 0
]

cases = []
for name, chain, signer, seat_no, n, m in CASES:
    pub = sb.pub_seed(chain, signer, seat_no)
    seed = fake("test seed/" + name)
    seat, safe, stx = addr(0x33), addr(0x44), fake("safe tx hash/" + name)
    next_seed = fake("test seed/" + name + "/next")
    next_key = sb.key_fingerprint(pub, n + 1, next_seed)
    c = sb.approval_hash(chain, seat, safe, n, stx)
    if m is None:
        m = sb.one_time_message(c, next_key)
    sig = sb.sign(pub, n, seed, m)
    ends = [sb.chain_end(pub, n, j, seed) for j in range(sb.CHAINS)]
    key = sb.key_fingerprint(pub, n, seed)
    assert sb.recover(pub, n, m, sig) == key
    cases.append({
        "name": name,
        "chainId": str(chain), "curveSigner": x(signer), "seatNumber": str(seat_no), "n": str(n),   # decimal strings: JSON numbers lose bits above 2**53 in JavaScript
        "pubSeed": x(pub),
        "prfSalt": x(sb.prf_salt(chain, signer, seat_no, n)),
        "seed": x(seed),
        "secret0": x(sb.secret(seed, 0)), "secret66": x(sb.secret(seed, 66)),
        "step0": x(sb.step(pub, n, 0, 0, sb.secret(seed, 0))),
        "end0": x(ends[0]), "end66": x(ends[66]),
        "key": x(key),
        "seat": x(seat), "safe": x(safe), "safeTxHash": x(stx),
        "nextSeed": x(next_seed), "nextKey": x(next_key),
        "c": x(c),
        "m": x(m), "digits": sb.digits(m), "checksum": sum(sb.STEPS - d for d in sb.digits(m)[:64]),
        "signature": [x(v) for v in sig],
        # what must NOT verify: each is a change to one input, and recover() must not give `key`
        "refused": [
            {"what": "another message", "m": x(sb.h(m))},
            {"what": "another key number", "n": str(n + 1)},
            {"what": "one value changed", "index": 5},
        ],
    })

out = {
    "about": "Sign and Burn v1 test vectors. Generated by generate.py from reference/python; reference/js and the contracts must agree on every value. Frozen: a change is a new tag, never an edit here. Every input is fake and public.",
    "version": 1,
    "parameters": {"w": 16, "chains": 67, "steps": 15, "signatureBytes": 67 * 32, "hash": "sha256"},
    "cases": cases,
}
with open(os.path.join(HERE, "v1.json"), "w") as f:
    json.dump(out, f, indent=1)
    f.write("\n")
print("wrote v1.json:", len(cases), "cases")
